services:
  mongo:
    image: mongo:latest
    container_name: product-system-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest-product-system
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
